import type { InstrumentSymbol } from "./instruments";

export type MarketRatioDefinition = {
  id: string;
  numerator: InstrumentSymbol;
  denominator: InstrumentSymbol;
  label: string;
  category: string;
  meaning: string;
  marketInterpretation: string;
};

export const MARKET_RATIOS: readonly MarketRatioDefinition[] = [
  {
    id: "sp500ew-gspc",
    numerator: "^SP500EW",
    denominator: "^GSPC",
    label: "S&P 500 EW / S&P 500 (^GSPC)",
    category: "Breadth",
    meaning: "Equal-weight breadth versus the S&P 500",
    marketInterpretation: "Rising suggests broader participation beyond mega-cap leaders and healthier market breadth; Falling suggests leadership is narrowing into the largest companies.",
  },
  {
    id: "rut-gspc",
    numerator: "^RUT",
    denominator: "^GSPC",
    label: "Russell 2000 (^RUT) / S&P 500 (^GSPC)",
    category: "Participation",
    meaning: "Small caps versus the large-cap market",
    marketInterpretation: "Rising suggests improving cyclical participation, economic confidence, and risk appetite; Falling suggests investors prefer large-cap defensiveness.",
  },
  {
    id: "w5000-gspc",
    numerator: "^W5000",
    denominator: "^GSPC",
    label: "Wilshire 5000 (^W5000) / S&P 500 (^GSPC)",
    category: "Breadth",
    meaning: "Broad US market participation versus the S&P 500",
    marketInterpretation: "Rising suggests strength is spreading across large, mid, and small US companies; Falling suggests market leadership is becoming increasingly concentrated.",
  },
  {
    id: "ndx-gspc",
    numerator: "^NDX",
    denominator: "^GSPC",
    label: "Nasdaq 100 (^NDX) / S&P 500 (^GSPC)",
    category: "Growth",
    meaning: "Growth and technology leadership versus the broad market",
    marketInterpretation: "Rising suggests growth and technology are leading investor returns; Falling suggests rotation toward value, cyclicals, or defensive sectors.",
  },
  {
    id: "hyg-ief",
    numerator: "HYG",
    denominator: "IEF",
    label: "High Yield Bonds (HYG) / 7-10Y Treasuries (IEF)",
    category: "Credit",
    meaning: "Credit risk appetite versus intermediate Treasury safety",
    marketInterpretation: "Rising suggests stronger risk appetite, easier credit, and improving confidence in corporate borrowers; Falling suggests caution or a flight toward Treasury safety.",
  },
  {
    id: "vix-vix3m",
    numerator: "^VIX",
    denominator: "^VIX3M",
    label: "VIX / VIX3M",
    category: "Volatility",
    meaning: "30-day versus 3-month expected S&P 500 volatility",
    marketInterpretation: "Above 1 means near-term expected volatility exceeds the 3-month horizon; Below 1 means near-term expected volatility is lower than the 3-month horizon.",
  },
  {
    id: "tlt-gspc",
    numerator: "TLT",
    denominator: "^GSPC",
    label: "20+ Year Treasuries (TLT) / S&P 500 (^GSPC)",
    category: "Rates",
    meaning: "Long-duration Treasuries versus equities",
    marketInterpretation: "Rising suggests investors favor defensive duration over equities, often as yields or growth expectations fall; Falling suggests equities lead bonds.",
  },
  {
    id: "dbc-gspc",
    numerator: "DBC",
    denominator: "^GSPC",
    label: "Commodities (DBC) / S&P 500 (^GSPC)",
    category: "Commodities",
    meaning: "Broad commodities versus equities",
    marketInterpretation: "Rising suggests stronger global cyclical demand and possible inflation pressure; Falling suggests softer growth expectations, weaker demand, or disinflation.",
  },
  {
    id: "gld-gspc",
    numerator: "GLD",
    denominator: "^GSPC",
    label: "Gold (GLD) / S&P 500 (^GSPC)",
    category: "Gold",
    meaning: "Gold and defensive demand versus equities",
    marketInterpretation: "Rising suggests defensive demand linked to inflation, currency concerns, or geopolitical risk; Falling suggests stronger preference for risk assets.",
  },
  {
    id: "uso-gspc",
    numerator: "USO",
    denominator: "^GSPC",
    label: "Oil (USO) / S&P 500 (^GSPC)",
    category: "Oil",
    meaning: "Oil exposure versus equities",
    marketInterpretation: "Rising suggests stronger energy demand, supply risk, or inflation pressure; Falling suggests weaker demand or easing energy costs.",
  },
  {
    id: "slv-gld",
    numerator: "SLV",
    denominator: "GLD",
    label: "Silver (SLV) / Gold (GLD)",
    category: "Metals",
    meaning: "Industrial silver demand versus monetary gold demand",
    marketInterpretation: "Rising suggests a more cyclical, industrial tone and stronger manufacturing demand; Falling suggests a more defensive preference for monetary metals.",
  },
  {
    id: "ung-gspc",
    numerator: "UNG",
    denominator: "^GSPC",
    label: "Natural Gas (UNG) / S&P 500 (^GSPC)",
    category: "Energy",
    meaning: "Natural gas exposure versus equities",
    marketInterpretation: "Rising suggests stronger power demand, supply concerns, or a tighter energy market; Falling suggests weaker demand or easing energy pressure.",
  },
  {
    id: "uup-gspc",
    numerator: "UUP",
    denominator: "^GSPC",
    label: "US Dollar (UUP) / S&P 500 (^GSPC)",
    category: "Dollar",
    meaning: "US dollar strength versus equities",
    marketInterpretation: "Rising suggests defensive demand, tighter global financial conditions, or pressure on emerging markets; Falling often supports global risk appetite.",
  },
  {
    id: "eem-gspc",
    numerator: "EEM",
    denominator: "^GSPC",
    label: "Emerging Markets (EEM) / S&P 500 (^GSPC)",
    category: "Global",
    meaning: "Emerging markets participation versus US equities",
    marketInterpretation: "Rising suggests improving global breadth, international participation, and risk appetite; Falling suggests continued US leadership or global caution.",
  },
  {
    id: "vnq-gspc",
    numerator: "VNQ",
    denominator: "^GSPC",
    label: "Real Estate (VNQ) / S&P 500 (^GSPC)",
    category: "Real estate",
    meaning: "Listed real estate versus equities",
    marketInterpretation: "Rising suggests improving rate sensitivity, property sentiment, and appetite for real assets; Falling suggests pressure from yields or weaker property conditions.",
  },
  {
    id: "psp-gspc",
    numerator: "PSP",
    denominator: "^GSPC",
    label: "Listed Private Equity (PSP) / S&P 500 (^GSPC)",
    category: "Private equity",
    meaning: "Listed private equity exposure versus US equities",
    marketInterpretation: "Rising suggests stronger appetite for illiquid, cyclical, and leveraged assets; Falling suggests tighter financial conditions or caution toward private markets.",
  },
  {
    id: "xle-gspc",
    numerator: "XLE",
    denominator: "^GSPC",
    label: "Energy Select Sector (XLE) / S&P 500 (^GSPC)",
    category: "Energy",
    meaning: "US energy companies versus the broad equity market",
    marketInterpretation: "Rising suggests energy-sector leadership, stronger commodity support, or inflation pressure; Falling suggests weaker energy leadership or easing inflation pressure.",
  },
];
